FROM public.ecr.aws/docker/library/nginx:1.23.3

COPY ./containers/nginx/nginx.conf  /etc/nginx/nginx.conf
COPY ./containers/nginx/default.conf  /etc/nginx/conf.d/default.conf
COPY ./containers/nginx/webapp.conf /etc/nginx/conf.d/webapp.conf

EXPOSE 8080

