version: '3'
services:
  db:
    image: mysql:5.7.12
    volumes:
      - ./containers/db/conf.d/:/etc/mysql/conf.d/
        #- ./containers/db/init.d:/docker-entrypoint-initdb.d/
      - ./:/host
      - ./storage/docker/db:/var/lib/mysql
      - ./storage/docker/db_logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: realne_auth_development
      MYSQL_USER: realne_auth_development
      MYSQL_PASSWORD: realne_auth_development
    ports:
      - 7221:3306

  db_testing:
    image: mysql:5.7.12
    volumes:
      - ./containers/db/conf.d/:/etc/mysql/conf.d/
        #- ./containers/db/init.d:/docker-entrypoint-initdb.d/
      - ./:/host
      - ./storage/docker/db_testing:/var/lib/mysql
      - ./storage/docker/db_testing_logs:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: realne_auth_testing
      MYSQL_USER: realne_auth_testing
      MYSQL_PASSWORD: realne_auth_testing
    ports:
      - 7222:3306

  webapp:
    image: 151874643243.dkr.ecr.us-west-2.amazonaws.com/realne-auth/webapp
    build:
      context: .
      dockerfile: Dockerfile.webapp
    working_dir: /webapp
    entrypoint: /usr/local/bin/php-fpm.sh
    environment:
      - APP_ENV=production
    volumes:
      - webapp:/webapp
      - ./.env.docker:/webapp/.env

  nginx:
    image: 151874643243.dkr.ecr.us-west-2.amazonaws.com/realne-auth/nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx
    working_dir: /webapp
    volumes:
      - webapp:/webapp
      - ./containers/nginx/webapp.conf.docker:/etc/nginx/conf.d/webapp.conf
    ports:
      - 8380:8080
    depends_on:
      - webapp

volumes:
  webapp:
    driver_opts:
      type: none
      device: .
      o: bind

